#!/bin/sh

curl -L https://github.com/dylanaraps/pfetch/archive/refs/tags/0.6.0.tar.gz > data.tar.gz
tar xvf *.tar.gz

# Change the directory to the pfetch repo
cd pfetch-0.6.0

# Apply patch to add the pur package manager
patch -p1 < $2/patches/0001-add-pur-package-manager.patch

mv pfetch $1/usr/bin/pfetch
